//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wheel.User.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wheel.User.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string aboutUs {
            get {
                return ResourceManager.GetString("aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string campaign {
            get {
                return ResourceManager.GetString("campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string car {
            get {
                return ResourceManager.GetString("car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string createAccount {
            get {
                return ResourceManager.GetString("createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tyres.
        /// </summary>
        public static string customTyres {
            get {
                return ResourceManager.GetString("customTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hündürlüyü (%).
        /// </summary>
        public static string dHeight {
            get {
                return ResourceManager.GetString("dHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diametri (Düym).
        /// </summary>
        public static string dRadius {
            get {
                return ResourceManager.GetString("dRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other fine products.
        /// </summary>
        public static string dRelated {
            get {
                return ResourceManager.GetString("dRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu qış təkəridir?.
        /// </summary>
        public static string dSeason {
            get {
                return ResourceManager.GetString("dSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi təkərlərin sayı.
        /// </summary>
        public static string dStock {
            get {
                return ResourceManager.GetString("dStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəziyyəti.
        /// </summary>
        public static string dUsage {
            get {
                return ResourceManager.GetString("dUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eni (mm).
        /// </summary>
        public static string dWidth {
            get {
                return ResourceManager.GetString("dWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy return.
        /// </summary>
        public static string easyReturn {
            get {
                return ResourceManager.GetString("easyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/Avtoteker.az/.
        /// </summary>
        public static string fbUrl {
            get {
                return ResourceManager.GetString("fbUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string featured {
            get {
                return ResourceManager.GetString("featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string featuredProducts {
            get {
                return ResourceManager.GetString("featuredProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND WHEELS &amp; TYRES.
        /// </summary>
        public static string findWheelTyre {
            get {
                return ResourceManager.GetString("findWheelTyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOR ALL VEHICLE TYPES.
        /// </summary>
        public static string forAll {
            get {
                return ResourceManager.GetString("forAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Season.
        /// </summary>
        public static string fourSeason {
            get {
                return ResourceManager.GetString("fourSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100% Guaranteed.
        /// </summary>
        public static string guaranteed {
            get {
                return ResourceManager.GetString("guaranteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string menuCatalog {
            get {
                return ResourceManager.GetString("menuCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string menuNew {
            get {
                return ResourceManager.GetString("menuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was error on sent email.
        /// </summary>
        public static string messageError {
            get {
                return ResourceManager.GetString("messageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message was sent successfully.
        /// </summary>
        public static string messageSuccess {
            get {
                return ResourceManager.GetString("messageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Models.
        /// </summary>
        public static string newModels {
            get {
                return ResourceManager.GetString("newModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tyre.
        /// </summary>
        public static string newTyre {
            get {
                return ResourceManager.GetString("newTyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Tyre.
        /// </summary>
        public static string oldTyre {
            get {
                return ResourceManager.GetString("oldTyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest to Oldest.
        /// </summary>
        public static string orderNewToOld {
            get {
                return ResourceManager.GetString("orderNewToOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest to Newest.
        /// </summary>
        public static string orderOldToNew {
            get {
                return ResourceManager.GetString("orderOldToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: High to Lower.
        /// </summary>
        public static string orderPriceHtL {
            get {
                return ResourceManager.GetString("orderPriceHtL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: Low to High.
        /// </summary>
        public static string orderPriceLtH {
            get {
                return ResourceManager.GetString("orderPriceLtH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string ourServices {
            get {
                return ResourceManager.GetString("ourServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string pre {
            get {
                return ResourceManager.GetString("pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products of.
        /// </summary>
        public static string productsOf {
            get {
                return ResourceManager.GetString("productsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string radius {
            get {
                return ResourceManager.GetString("radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return &amp; Exchange.
        /// </summary>
        public static string returnExchange {
            get {
                return ResourceManager.GetString("returnExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round-the-clock free hotline (24/7).
        /// </summary>
        public static string roundClock {
            get {
                return ResourceManager.GetString("roundClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string sale {
            get {
                return ResourceManager.GetString("sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to satisfaction.
        /// </summary>
        public static string satisfaction {
            get {
                return ResourceManager.GetString("satisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all products.
        /// </summary>
        public static string seeAll {
            get {
                return ResourceManager.GetString("seeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owning the tires with wide range of sizes and quality is a lot easier with us. Our company supplies the tires with the highest quality from Europe and Asia in minimum time intervals in line with your orders. 
        ///Contact us, if you are also in favor of quality. We are constantly active for the customers to be able to be in contact with us anytime they need. Please, contact us in 7 days of a week.The active hours of our store: 9:00-19:00..
        /// </summary>
        public static string servicesText1 {
            get {
                return ResourceManager.GetString("servicesText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customers,
        ///Distance is not an obstacle for us to make you satisfied any more. It is enough to call us or communicate via online services from any region of Azerbaijan Republic. We aim the provosion of comfort for you by delivering any product you are in want of to your adress. This is not the end...We are fullfilling the balancing and replacement of the tires of your cars ¬¬¬which will be provided by our professional personnel according to the maximum quality standards. We guarantee the accuracy of bal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string servicesText2 {
            get {
                return ResourceManager.GetString("servicesText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking about of you we started the online activities of our company. Dear customers,our goal is to create possibility for you to achieve the desired product in any time without any additional cost. Through the online site you can get information very quickly about the product that if it is based in the firm or not, get information about various compaigns existing in the firm and to contact with us. Also you can order the desired product without going any distance. You can use our site without any borders, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string servicesText3 {
            get {
                return ResourceManager.GetString("servicesText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales tires.
        /// </summary>
        public static string servicesTitle1 {
            get {
                return ResourceManager.GetString("servicesTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance and delivery.
        /// </summary>
        public static string servicesTitle2 {
            get {
                return ResourceManager.GetString("servicesTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Site.
        /// </summary>
        public static string servicesTitle3 {
            get {
                return ResourceManager.GetString("servicesTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 Day.
        /// </summary>
        public static string sevenDay {
            get {
                return ResourceManager.GetString("sevenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Now.
        /// </summary>
        public static string shopNow {
            get {
                return ResourceManager.GetString("shopNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Campaign Tyres.
        /// </summary>
        public static string showTyres {
            get {
                return ResourceManager.GetString("showTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyres.
        /// </summary>
        public static string siteName {
            get {
                return ResourceManager.GetString("siteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online tyres store.
        /// </summary>
        public static string siteSlogan {
            get {
                return ResourceManager.GetString("siteSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by.
        /// </summary>
        public static string sortBy {
            get {
                return ResourceManager.GetString("sortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Reamining.
        /// </summary>
        public static string stockRemain {
            get {
                return ResourceManager.GetString("stockRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string summer {
            get {
                return ResourceManager.GetString("summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/avtoteker17/.
        /// </summary>
        public static string twitterUrl {
            get {
                return ResourceManager.GetString("twitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyres.
        /// </summary>
        public static string tyres {
            get {
                return ResourceManager.GetString("tyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tyres.
        /// </summary>
        public static string tyresHome {
            get {
                return ResourceManager.GetString("tyresHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused.
        /// </summary>
        public static string unused {
            get {
                return ResourceManager.GetString("unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Status.
        /// </summary>
        public static string usage {
            get {
                return ResourceManager.GetString("usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string used {
            get {
                return ResourceManager.GetString("used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all collections.
        /// </summary>
        public static string viewAll {
            get {
                return ResourceManager.GetString("viewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string winter {
            get {
                return ResourceManager.GetString("winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string yourName {
            get {
                return ResourceManager.GetString("yourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://youtube.com.
        /// </summary>
        public static string ytUrl {
            get {
                return ResourceManager.GetString("ytUrl", resourceCulture);
            }
        }
    }
}
