//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wheel.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class slider
    {
        public int id { get; set; }
        public string style { get; set; }
        public string imgPath { get; set; }
        public string az { get; set; }
        public string ru { get; set; }
        public string en { get; set; }
        public string linkUrl { get; set; }
    }
}
